# Handoff to the Python CLI.
#
# Terraform can build every resource in this project but it cannot run
# StartIngestionJob -- there is no such resource in the AWS provider. So `kb
# ingest`, `kb eval`, `kb ask`, and `kb compare` still do the rest of the
# pipeline, and they find resources through two generated files:
#
#   kb-state.json     the same shape aws.save_state() writes, so resolve() works
#   config.tf.yaml    config.yaml with two keys overridden, so the CLI addresses
#                     *this* stack rather than the one `kb provision` built
#
# Neither is source; both are gitignored and rebuilt by every apply.

resource "local_file" "kb_state" {
  filename = "${path.module}/../${var.state_file_rel}"

  # Same keys as provision.provision() saves, so nothing in the Python code has
  # to know a Terraform stack exists.
  content = jsonencode({
    for k in keys(local.selected) : k => {
      region            = local.region
      role_arn          = aws_iam_role.kb[k].arn
      knowledge_base_id = aws_bedrockagent_knowledge_base.kb[k].id
      data_source_id    = aws_bedrockagent_data_source.kb[k].data_source_id
      corpus_bucket     = local.corpus_bucket
    }
  })
}

# config.yaml is the single source of truth, so this is derived from it rather
# than being a second copy: read, override two keys, re-emit. Adding a key to
# config.yaml propagates here on the next apply.
#
# The two overrides are the two things that must differ for a parallel stack:
#   aws.project_prefix   so the CLI computes this stack's resource names
#   paths.state_file     so it reads kb-state.json above instead of the Python
#                        stack's .kb-state.json
#
# `default_experiments` is narrowed to what this stack actually built, so a bare
# `kb ingest` cannot reach for an experiment Terraform did not create.
#
# Comments are lost -- yamlencode emits data, not formatting. That is why this is
# a generated artifact and config.yaml stays the file you edit.
resource "local_file" "kb_config" {
  filename = "${path.module}/../${var.rendered_config_rel}"

  content = join("\n", [
    "# GENERATED by terraform/handoff.tf -- do not edit.",
    "#",
    "# config/config.yaml with aws.project_prefix and paths.state_file overridden",
    "# to address the Terraform-built stack. Edit config/config.yaml and re-apply.",
    "#",
    "# Usage:  KB_CONFIG=${var.rendered_config_rel} uv run kb ingest all",
    yamlencode(merge(local.cfg, {
      aws                 = merge(local.cfg.aws, { project_prefix = local.project })
      paths               = merge(local.cfg.paths, { state_file = var.state_file_rel })
      default_experiments = sort(keys(local.selected))
    })),
  ])
}
